<?php
require('fpdf/fpdf.php');

class PDF extends FPDF
{
// Page header
function Header()
{
    // Logo
    $this->Image('FA Logo.jpg',0,10,20);
    // Arial bold 15
    $this->SetFont('Arial','B',10);
    // Move to the right
	$this->Cell(15);
	 $this->Cell(30,10,'Faculty Association,Inc.',0,0,'C');
	 $this->Ln(5);
	 $this->Cell(19);
	 $this->SetFont('Arial','',10);
	$this->Cell(30,10,'De La Salle University - Manila',0,0,'C');
    $this->Cell(80);
    // Title
   
    $this->Ln(20);
}

// Page footer
function Footer()
{
     $this->SetY(-20);
    // Arial italic 8
    $this->SetFont('Arial','I',8);
    // Page number
    $this->Cell(0,5,'Page '.$this->PageNo().' of {nb}',0,0,'C');
	$this->ln();
	 $this->SetFont('Arial','',8);
	$this->Cell(0,5,'FACULTY ASSOCIATION',0,1,'C');
	$this->Cell(0,5,'2401 Taft Avenue, Malate, Manila Philippines',0,1,'C');
	$this->Cell(0,5,'(632) 524-4611 Ext. 332',0,1,'C');
}
}

// Instanciation of inherited class
$pdf = new PDF();
$pdf->AliasNbPages();
$pdf->AddPage();
$pdf->SetFont('Times','B',10);
$pdf->Cell(0	,5,"General Overall Deductions"	,0,1,'C');

$pdf->SetFont('Times','',10);
$pdf->Cell(0	,5,"Generated by Melton at ".date("m/d/Y")." ".date("h:i:sa")	,0,1,'C');
$pdf->ln();
$pdf->Cell(10);
$pdf->SetFont('Times','B',10);
$pdf->Cell(20,5,''	,'L,T,R',0);
$pdf->Cell(80	,5,''	,'L,T,R',0,'L');
$pdf->Cell(50	,5,''	,'L,T,R',0,'R');
$pdf->Cell(25	,5,'Total Salary '	,'L,T,R',0,'R');
$pdf->ln();
$pdf->Cell(10);
$pdf->Cell(20,5,'ID Number '	,'L,B,R',0,'C');
$pdf->Cell(80	,5,'Full Name'	,'L,B,R',0,'L');
$pdf->Cell(50	,5,'Department'	,'L,B,R',0,'C');
$pdf->Cell(25	,5,'Deduction'	,'L,B,R',0,'R');
$pdf->ln();
$pdf->SetFont('Times','',10);
require_once('mysql_connect_FA.php');
$flag=0;
$query="SELECT m.member_ID as 'ID', firstname as 'First',lastname as 'Last',middlename as 'Middle',DEPT_NAME,sum(t.amount) as 'Total'
from member m
join ref_department d
on m.dept_id = d.dept_id
join txn_reference t
on t.MEMBER_ID = m.MEMBER_ID
join (SELECT max(txn_date) as 'Date' from txn_reference where txn_type = 2) latest
where TXN_TYPE =2 and latest.Date = txn_date
group by m.member_ID";
	
$result=mysqli_query($dbc,$query);


while($row=mysqli_fetch_assoc($result)){
$last = $row['LAST'];
$first = $row['FIRST'];
$middle = $row['MIDDLE'];







$pdf->Cell(10);
$pdf->Cell(20,5,$row['ID']	,1,0,'C');
$pdf->Cell(80	,5,"$last, $first $middle"	,1,0,'L');


$total = sprintf("%.2f",$total);

$pdf->Cell(50	,5,"{$row['Dept_Name']}"	,'L,B,R',0,'C');
$pdf->Cell(25	,5,"{$row['Total']}"	,1,0,'R');
$pdf->ln();



}

$pdf->SetFont('Times','B',12);

$pdf->Cell(0	,5,"--END OF REPORT--"	,0,0,'C');
$pdf->Output();
?>